import {
  REACT_APP_ORDERS_API_HOST,
  REACT_APP_CATALOG_API_URL,
  REACT_APP_AUTH_API_URL,
  REACT_APP_ORDERS_API_PROVIDER,
  REACT_APP_CDN_URL
} from '@env';

const env =  {
  REACT_APP_ORDERS_API_HOST,
  REACT_APP_CATALOG_API_URL,
  REACT_APP_AUTH_API_URL,
  REACT_APP_ORDERS_API_PROVIDER,
  REACT_APP_CDN_URL
};

console.log(env);

export default env;