name: e2e tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start containers
      run: docker-compose up -d --build
    - name: Stop containers
      if: always()
      run: docker-compose down
