# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET apps

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./apps/shop.app.catalog.api
      run: dotnet restore
    - name: Build
      working-directory: ./apps/shop.app.catalog.api
      run: dotnet build --no-restore
    - name: Build Test
      working-directory: ./apps/shop.app.catalog.api.tests
      run: dotnet build
    - name: Test
      working-directory: ./apps/shop.app.catalog.api.tests
      run: dotnet test --no-restore --verbosity normal 
