name: Node.js apps

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Shop.App.Web Tests
        working-directory: ./apps/shop.app.web
        
        run: |
          npm install
          npm run lint
          npm run test

      - name: Shop.App.Orders.Api Tests
        working-directory: ./apps/shop.app.orders.api
        run: |
          npm ci
          npm run lint
          npm run test
